### ISSUE TITLE
check if stdout is a tty

### ISSUE THREAD

**Issue by lilydjwg** [wting/autojump#132]
I'm using zsh. Once I enjoyed something like this:

```
mv file `j backup`
```

And I just pressed `Tab` to expand the jump to see if it was what I wanted.

But now, I get something like `$'\033'\[31m/home/lilydjwg/data/backup$'\033'\[0m` instead of a plain path. I think the script should disable color output if stdout is not a tty.

**Comment by kuerzn** [comment]
This is the same problem as #377. i.e. not fixed
