### ISSUE TITLE
Prints directory to jump to, but doesn't change directory

### ISSUE THREAD

**Issue by zdravi** [wting/autojump#138]
I've been attempting to get this work under Mac OS X and zsh with no success so far. I'm running Mac OS X 10.6.8 with a base installed Python version of 2.6.1. I've tried 
- installing the old version 17 and using it with 2.6.1.
- getting the most recent version from git, upgrading Python, adding the python3 location to my path, and changing the python location in the autojump to python3's location
- installing the version MacBrew hands out by default (v20).

All of them end up in the same state: working, showing the directory it would jump to, and then not jumping. Is this an inherent Mac problem? I'm not having this issue on Ubuntu...

**Comment by jrr** [comment]
In case this happens to anyone else:

I had hastily set up a fish abbreviation to turn `j` into `autojump`. Don't do that.

`autojump` and `j` have two different meanings, both provided by the fish installation.

**Comment by AaronWang** [comment]
remove 
alias j='autojump'
solved my problem, j  works
