### ISSUE TITLE
j function not found

### ISSUE THREAD

**Issue by brycepg** [wting/autojump#144]
Ubuntu server edition 11.04
Python2.7

It looks like somehow `/usr/share/autojump/autojump.zsh` wasn't not being sourced; I opened up bash and its equivalent wasn't not either. I modified `/usr/share/autojump/autojump.sh` to see if the conditions were not being met but that file wasn't being sourced too.

To workaround this, I directly sourced autojump.zsh in .zshrc, and so now `j` works fine for me.

**Comment by cnlzxin** [comment]
reboot

It works for me
