### ISSUE TITLE
autocomplete option don't work with zsh and oh-my-zsh

### ISSUE THREAD

**Issue by reyman** [wting/autojump#152]
I recently install oh-my-zsh , after a recent git pull of autojump on master branch ( commit 16e0c51bae6d1ff4948d39ba57ced1b0e79bee06  ) and a reinstall with .install.sh --zsh option, i add this to my .zshrc 

```
autoload -U compinit
compinit
source $ZSH/oh-my-zsh.sh
[[ -s ~/.autojump/etc/profile.d/autojump.zsh ]] && source ~/.autojump/etc/profile.d/autojump.zsh
```

After a restart, and a source .zshrc, i have the sample problem with TAB completion :(  

```
 Unknown command line argument: option --complete not recognized
```

**Comment by anrao91** [comment]
My fix for this issue is - 
1) Execute the zshrc in the bash first, and then change the SHELL, say -
$~/.zshrc
$ZSH
#Provided you have followed the installation steps given here - https://github.com/robbyrussell/oh-my-zsh/blob/master/README.markdown
