### ISSUE TITLE
autojump displays a directory, but does not cd to it

### ISSUE THREAD

**Issue by alexbw** [wting/autojump#154]
autojump --stat correctly displays directories I've changed to, and using autojump or the aliased "j" command displays the correct directory, but never changes to it. 

I have tried a homebrew install, and a manual install, and have double-checked that I'm sourcing correctly. 

I'm running 10.8 on a mid-2012 Mac Pro.

**Comment by stephenluu** [comment]
I make an alias "j = autojump " , cause the same question . Thanks any way .

**Comment by wting** [comment]
@stephenluu: You're not supposed to call autojump directly, but rather source the relevant shell (e.g. [bash](https://github.com/joelthelion/autojump/blob/master/bin/autojump.bash)). This is setup when you run `./install.py`.

**Comment by turing-king** [comment]
How to solve it?
