### ISSUE TITLE
zsh: command not found: j

### ISSUE THREAD

**Issue by shepherdwind** [wting/autojump#196]
I install autojump by brew, run command

``` sh
$ brew install autojump
```

But, there are some problem with me. First, I can only run the command `autojump`, the `j` is not found when I run it. Then, I run `autojump -a ~/code`, return error message:

```
  File "/usr/local/bin/autojump", line 176, in save
    temp = NamedTemporaryFile(dir = CONFIG_DIR, delete = False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 447, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 228, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/Users/eward/.local/share/autojump/tmprYDreK
```

/Users/eward is my home dir. I think the problem is the tmp file is not writeable, So I create the dir `~/.local/share/autojump` for autojump. Now, the autojump --add is ok, but j is not available.

Then from issue #178 I find out that, my .zshrc should include the etc file of autojump, And I add it to my .zshrc file

```
source $HOME/homebrew/Cellar/autojump/21.1.2/etc/autojump.zsh
```

Final, autojump is work, but, I do not know, if so much trouble is because of what. May be, there is a bug, or may someone face the same problem with me. I hope this can helpful.

**Comment by divs1210** [comment]
@wting facing this issue with brew + autojump v22.5.1 + zsh + tmux

**Comment by ical10** [comment]
> Try adding this to your .zshrc:
> 
> ```
> [[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
> ```

this one solved it for me. Mojave, zsh 5.3, autojump 22.5.3

**Comment by Swchexit** [comment]
> > Try adding this to your .zshrc:
> > ```
> > [[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
> > ```
> 
> this one solved it for me. Mojave, zsh 5.3, autojump 22.5.3

Autojump is working fine on my old 2014 mac(big sur), but when i transfer to a m1 pro mbp, this happened.
Luckily, adding this line to .zshrc fix it.
macbook pro w/ m1 pro, Monterey, zsh5.8, autojump 22.5.3

**Comment by medev21** [comment]
`[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
`

Looks like this command has changed at some point, but as of now it's a bit different.

After installing autojump with brew, `brew install autojump`

run `brew info autojump`

it will print out the edit you need to make in your .zshrc/bash file

reference -> [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
