### ISSUE TITLE
Bad bash tab completion 

### ISSUE THREAD

**Issue by cipri-tom** [wting/autojump#228]
Hi. Thanks a lot for autojump!

Tab completion doesn't seem to work too well on my machine. 
I have the following stats:

```
...
14.3:   /home/cipri/Documents
...
220.8:  /home/cipri/Documents/work
```

When I type `j doc<tab>` it shows `j '/home/cipri/Documents'` but if I type
`j wor<tab>` it gets completed in `j 'wor__`. Although it still works, it is not very helpful and I cannot understand why.

I have included `[[ -s /etc/profile.d/autojump.bash ]] && . /etc/profile.d/autojump.bash` in my .bashrc.

**Comment by mpacer** [comment]
This still seems to be an issue?
