### ISSUE TITLE
Implement smart case

### ISSUE THREAD

**Issue by PythonNut** [wting/autojump#239]
In vim, the option smartcase sets searches to case-insensitive only if they have no uppercase characters. If uppercase characters are present, the search is conducted case sensitive. "ab" matches all case variations, and "Ab" matches "Ab" only.

Another option is this behaviour of zsh completion

```
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
```

Here, lowercase characters can stand for uppercase characters, but not vice-versa. So, the toggling of case is on a per-character basis. Here "ab" matches all case permutations, and "Ab" matches both "Ab" and "AB", but not "ab".

The rationale behind this is as follows: If the user expends the effort to type in the correct case, the search system should try use that extra effort to reduce ambiguity. 

Is this already possible? And, if not, does it sound like a useful feature?

Thanks,
PythonNut

**Comment by caseycronyn** [comment]
Apologies for reviving a closed thread but how do I enable smartcase detection? This doesn't seem to be working for me
