### ISSUE TITLE
autojump losing settings/database?? /cry

### ISSUE THREAD

**Issue by chrishough** [wting/autojump#285]
This may seem like an odd issue + it's hard to describe. I loved this tool, but recently it feels like it is losing my settings constantly.  I have these settings in my bash setup that a friend told me were required so I wanted to mention them to inquire if they have something to do with it.  Is there anything else I can provide to help with this? 

Thank you so much for your help. Let me know if I can gittip ya or something. 

Cheers.

```
# ZSH Autocomplete
autoload -U compinit && compinit
```

**Comment by danielecook** [comment]
This happens for me frequently. I have to go and move the backup database in place and it fixes it. I am on an HPC btw.
