### ISSUE TITLE
autojump: error: unrecognized arguments: -l

### ISSUE THREAD

**Issue by etaf** [wting/autojump#306]
%j -v
autojump v22.0.0-alpha

% j -s
autojump: error: unrecognized arguments: -l

% j
usage: autojump [-h] [-a DIRECTORY] [-i [WEIGHT]] [-d [WEIGHT]] [--complete]
                [--purge] [-s] [-v]
                [DIRECTORY [DIRECTORY ...]]
autojump: error: unrecognized arguments: -l

**Comment by bisque33** [comment]
I also happened the same error.
I didn't know what has been set `alias j="jobs -l"` anywhere.
However, it was resolved by adding `alias j="jobs"`to the .zshrc.
