### ISSUE TITLE
How should distribution package the latest autojump?

### ISSUE THREAD

**Issue by Siosm** [wting/autojump#338]
Distributions (Arch Linux example: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/autojump) use this kind of command to package autojump:

```
$ ./install.py --destdir "${pkgdir}" --prefix 'usr/' --zshshare 'usr/share/zsh/site-functions'
```

But this creates broken '/etc/profile.d/autojump.sh' config files with a custom path dependent on the compile time folder location and not the actual prefix location (example from a custom build on my system):

```
# the login $SHELL isn't always the one used
# NOTE: problems might occur if /bin/sh is symlinked to /bin/bash
if [ -n "${BASH}" ]; then
    shell="bash"
elif [ -n "${ZSH_NAME}" ]; then
    shell="zsh"
elif [ -n "${__fish_datadir}" ]; then
    shell="fish"
elif [ -n "${version}" ]; then
    shell="tcsh"
else
    shell=$(echo ${SHELL} | awk -F/ '{ print $NF }')
fi

# prevent circular loop for sh shells
if [ "${shell}" = "sh" ]; then
    return 0

# check local install
elif [ -s ~/.autojump/share/autojump/autojump.${shell} ]; then
    source ~/.autojump/share/autojump/autojump.${shell}

# check global install
elif [ -s /usr/local/share/autojump/autojump.${shell} ]; then
    source /usr/local/share/autojump/autojump.${shell}

fi

# check custom install         
if [ -s /home/tim/projects/perso/asp/autojump/repos/community-any/pkg/autojump/etc/profile.d/autojump.${shell} ]; then             
    source /home/tim/projects/perso/asp/autojump/repos/community-any/pkg/autojump/etc/profile.d/autojump.${shell}         
fi
```

The expected custom section:

```
# check custom install         
if [ -s /usr/share/autojump/autojump.${shell} ]; then             
    source /usr/share/autojump/autojump.${shell}         
fi
```

Fixing this is more than just replacing 'etc_dir' by 'share_dir' in install.py:210 (which might be a good thing to do too), so I'm asking for inputs.

**Comment by wting** [comment]
I've fixed `modify_autojump_sh()` in fa3ff58d. Can you guys check if this is still a problem in the latest version?

**Comment by mineo** [comment]
It's still a problem because `autojump.sh` will still try to source files from `destdir` (like `/home/wieland/dev/PKGBUILDS/autojump-git/pkg/autojump-git/usr/share/autojump/autojump.${shell}` when the file really is in just `/usr/share/autojump/autojump.${shell}`) which (according to the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/DESTDIR.html#DESTDIR)) should not actually appear in installed files at all.

**Comment by youtux** [comment]
@wting Could you please tag the latest version on git? (And maybe also all the future releases). In this way I can test using the brew formula properly, and open a pull request for the new version. Thanks

**Comment by wting** [comment]
Sorry, forgot about; done!

**Comment by youtux** [comment]
@wting can't still see it. Maybe you forgot to push?

**Comment by wting** [comment]
I accidentally only pushed it to my fork (which I use for dev). Just pushed it to this repo.

**Comment by 0-wiz-0** [comment]
I had problems packaging as well, and found this issue. Let me know if I should open a separate issue for this:

I wanted to use 'install.py -fs -p /usr/pkg -d ${SOMETMPDIR}' but get
````
Custom paths incompatible with --system option.
````
When I try without '-fs', destdir is ignored:
````
Installing autojump to /usr/obj/shells/autojump/work/.destdir ...
creating directory: /usr/pkg/bin
creating directory: /usr/pkg/share/man/man1
Traceback (most recent call last):
  File "install.py", line 214, in <module>
    sys.exit(main(parse_arguments()))
  File "install.py", line 177, in main
    mkdir(doc_dir, args.dryrun)
  File "install.py", line 29, in mkdir
    os.makedirs(path)
  File "/usr/pkg/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/pkg/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/pkg/share/man'
*** Error code 1
````

Please let me know what the proper invocation is.

**Comment by Siosm** [comment]
Closing as this will probably never happen. Feel free to reopen / open your own issue if needed.
