### ISSUE TITLE
'jo' to Open a Directory in File Browser doesn't work

### ISSUE THREAD

**Issue by voidl** [wting/autojump#342]
AutoJump is working great in Fish with oh-my-fish and iTerm2. Installed via Brew.
But 'jo' jump and open in browser always returns this error:

```fish
 ✘  ~  jo users
autojump: directory 'users' not found
\n/Users\n
Try `autojump --help` for more information.
```

**Comment by bryanbecker** [comment]
I found the solution to this problem.  In autojump.fish, the definition of `jo` has a logical error.  It checks if the directory exists, but has the if/else conditions swapped (i.e. it displays error message on success, and tries to do the jump on fail).

If you manually edit it, just swap what's between the if and the else

**Comment by spinningarrow** [comment]
I'm getting this issue on the latest version (`22.2.4`). Pull request welcome?

**Comment by marcecj** [comment]
Wasn't this fixed in f09d23e30d3159db18872a3e8f8f579ed9e77231?

**Comment by spinningarrow** [comment]
@marcecj I can't explain it but I'm **not** getting the error any more. I'm still on `v22.2.4` :sweat_smile:

**Comment by voidl** [comment]
All working fine for me!

**Comment by marcecj** [comment]
@spinningarrow: Yeah, I'm not getting the error either, but that's because Gentoo carries the patch from the commit I referenced above, which is why I was asking.  The fix should be in the current release, so I was wondering why this bug is still open :-) .
