### ISSUE TITLE
Unable to make it work for fish-shell in Fedora as saying in ducumentation

### ISSUE THREAD

**Issue by c02y** [wting/autojump#344]
I tried to install `autojump` using `yum` or manually `./install.py`, but I cannot make it work for fish-shell as saying in documentation, `autojump -s` list no directories, and `j` is not even a command in fish.

FYI:
Fedora 21
fish 2.1.1

**Comment by idoo** [comment]
works fine for me now

if it still doesn't work: did you add:

```
 [ -f /usr/local/share/autojump/autojump.fish ];⋅
  2 source /usr/local/share/autojump/autojump.fish⋅
```
to your fish file?

**Comment by c02y** [comment]
It was three years ago, I don't use autojump anymore, never used. 

Thanks.

**Comment by wting** [comment]
Thanks for helping out @idoo.

@c02y: Sorry it didn't work out. :(
