### ISSUE TITLE
Remove directory from commany line

### ISSUE THREAD

**Issue by graywen24** [wting/autojump#394]
Hi all,
  I think what i want to ask here is more just a question as i didnt find from googling.

I use j -a [directory] to add path to the autojump database. while I want to remove it seems there is no parameter for it. I checked man page same as well.
So the only way I found is to remove the line from ~/Library/autojump/autojump.txt

is there is any way I can remove the added directory?
(I tried to uninstall and install again .. it doesnt work.)

17.3205080757   /Users/xxxx/homeMac/mac_doc
26.4575131106   /Users/xxxx/homeMac
17.3205080757   /var
10.0    /Users/xxxx/homeMac/mac_doc/zsh
~

"~/Library/autojump/autojump.txt" 4L, 138C

**Comment by jared-hess** [comment]
It appears that the only way to do this currently is to delete the corresponding line from the autjump.txt file, located at "~/Library/autojump/autojump.txt". 

I've added this functionality in my fork but have yet to merge it, check it out if you like:
https://github.com/jared-hess/autojump/tree/delete-entry

**Comment by wting** [comment]
Unless there's a lot of demand for this functionality, I'm inclined to prefer users to modify the source data itself. The text file is pretty easy to understand, and trying to predict what people are trying to delete based off a search is more error prone / higher cost of failure (compared to changing directories).

This is no different than removing an entry from `~/.bash_history`.

**Comment by graywen24** [comment]
thanks all...
close it hahaha....

**Comment by pedro-nonfree** [comment]
To remove a directory... or to prevent writing a directory on autojump database

after thinking for a while, I arrived to this solution in bash, that is: to avoid entire sessions being saved by autojump

.bashrc
```
if [ $NO_AUTOJUMP ]; then
    echo -en "\nno autojump\n"
else
    # database is in: ~/.local/share/autojump
    . /usr/share/autojump/autojump.sh
fi

# (...)
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
```

~/.bash_aliases
```
alias bashnj='NO_AUTOJUMP=1 bash'
```

**Comment by blasco** [comment]
I find this functionality also useful

**Comment by Victorcorcos** [comment]
I want that too. I'm constantly enterring in a unwanted directory while I was preferring to enter on another one and after some spikes, I believe the best solution would be to remove the annoying directory from being saved on `autojump`.

**Comment by Flimm** [comment]
For lurkers, the file to edit is `~/.local/share/autojump/autojump.txt` on Linux. Delete the line with the directory you want to remove from autojump's history.

You can also experiment with autojump `--decrease` and `--increase` flags, which decrease and increase the current directory weight, respectively. You can use the `--purge` flag to delete non-existant paths from the database.
