### ISSUE TITLE
Formatting of "Type/Name(s)" Tables is confusing

### ISSUE THREAD

**Issue by burblebee** [wting/autojump#406]
Table 151 "Header <cstdio> synopsis" in [c.files] and others like it throughout the spec have header "Type     Name(s)", but the contents don't line up with the headers.  It ends up looking like the entries in the far left column are "Type"s and all other entries are "Name(s)".  It would be clearer if the "Macros:"/"Functions:"/etc. appeared under "Type", and name entries appeared under "Name(s)".

**Comment by bendem** [comment]
#405 
Please @burblebee, this is the 3rd time you opened an issue on the wrong repo. This is not https://github.com/cplusplus/draft

**Comment by burblebee** [comment]
My apologies.  Issue moved to https://github.com/cplusplus/draft/issues/688
