### ISSUE TITLE
How to interpret Table 152 "Header <cinttypes> synopsis"?

### ISSUE THREAD

**Issue by burblebee** [wting/autojump#407]
How is one supposed to read and interpret the the macros in Table 152 "Header <cinttypes> synopsis" in 27.11 [c.files]?

**Comment by bendem** [comment]
#405 
Please @burblebee, this is the 3rd time you opened an issue on the wrong repo. This is not https://github.com/cplusplus/draft

**Comment by burblebee** [comment]
My apologies.  Issue moved to https://github.com/cplusplus/draft/issues/689
