### ISSUE TITLE
implementation-defined vs. implementation defined vs. impldef

### ISSUE THREAD

**Issue by burblebee** [wting/autojump#408]
The spec is inconsistent in the text for implementation-defined wording.  Some use the impldef reference, some use implementation-defined, and some use implementation defined.  It is also inconsistent in whether or not an index accompanies the implementation-defined text.

**Comment by bendem** [comment]
#405 
Please @burblebee, this is the 3rd time you opened an issue on the wrong repo. This is not https://github.com/cplusplus/draft

**Comment by burblebee** [comment]
My apologies.  Issue moved to https://github.com/cplusplus/draft/issues/687.
