### ISSUE TITLE
Installing from mac

### ISSUE THREAD

**Issue by willgdjones** [wting/autojump#409]
Installing with homebrew needs a few other explanation steps as it doesn't work out of the box.

Had to search around to source the correct file.

https://www.quora.com/How-can-I-source-autojump-a-very-handy-tool-used-in-directory-jumping-in-Mac-OS

Thanks a lot though it's a cool tool!

**Comment by najamkhn** [comment]
You just have to do `brew info autojump` and follow the instructions.

**Comment by wting** [comment]
@najamkhn Thanks for helping out!

Related to #416.

**Comment by banshengbushu** [comment]
so  cool!!!

**Comment by Shwetabh1** [comment]
This needs to be added in the readme for mac installation as this step is essential.
