### ISSUE TITLE
fail to enter the directory but show the PATH

### ISSUE THREAD

**Issue by ivanberry** [wting/autojump#413]
I am on MAC, and install zsh with autojump, after adding: 

> [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

>  plugins=(git bundler autojump osx rake ruby)

> alias  j="autojump"

this is the output of`j dev`: 

```bash
   # xx@xx ~ [14:02:29] $ j dev
             /Users/xx/Documents/dev/mum_union
```

Yeah, the autojump works, and also the alias `j` works too，but it didnot help me to the directory but show its PATH!

please give some tips 👍  😭 , BTW, THX for the great tool.

**Comment by bendem** [comment]
Your alias overrides the `j` command, remove it.

Also, https://github.com/wting/autojump/issues/397, https://github.com/wting/autojump/issues/302, https://github.com/wting/autojump/issues/29, https://github.com/wting/autojump/issues/229 all contain the same answer phrased a bit differently.

**Comment by wting** [comment]
Thanks for the help @bendem! This issue constantly comes up all the time so I need to tackle it head on. I've dumped some of my thoughts on fixing it in #416.

**Comment by ivanberry** [comment]
THX you guys all, I should Google more before open this issue! sorry for bother. :bow:
