### ISSUE TITLE
Lacks compatibility with Android/Termux

### ISSUE THREAD

**Issue by rbreaves** [wting/autojump#417]
I made a few modifications to get it to work on my system, but it would break the area of the code that prevents autojump from installing on unsupported shells. I am not sure why it thinks Termux is unsupported when I am trying to install autojump from zsh but that is what occurs.

Typing in echo $0 clearly outputs zsh as the shell and the code says it should work, but something is causing it fail.

Also the other thing that has to change for this install to work correctly is the '#!/usr/bin/evn' line needs to say '#!/system/xbin/evn' (the android user will need busybox installed).

**Comment by wting** [comment]
Probably because it's using `echo $SHELL` to check shell.

You're more than welcome to maintain a fork that has Android terminal support, but given the small user base and incompatible customizations I'm not inclined to merge related patches.
