### ISSUE TITLE
Unicode character error

### ISSUE THREAD

**Issue by vlachoudis** [wting/autojump#420]
Probably I have some directory in the list with some character that autojump doesn't like.
How can I remove the directory without destroying the database?

```
$ autojump 
Traceback (most recent call last):
  File "/usr/bin/autojump", line 420, in <module>
    sys.exit(main(parse_arguments()))
  File "/usr/bin/autojump", line 386, in main
    entries = entriefy(load(config))
  File "/usr/lib/python2.7/site-packages/autojump_data.py", line 80, in load
    ifilter(correct_length, imap(parse, f))))
  File "/usr/lib/python2.7/site-packages/autojump_data.py", line 70, in <lambda>
    tupleize = lambda x: (x[1], float(x[0]))
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-16361: invalid decimal Unicode string
```

**Comment by wting** [comment]
If you don't have _that_ many Unicode paths, you can fand remove the individual entry the autojump data file: `~/.local/share/autojump/autojump.txt`. If you're on OS X it's in: `~/Library/autojump/<something>`

**Comment by vlachoudis** [comment]
I've opened the autojump.txt and it was corrupted. It had several kb of garbage and then it was followed by the normal weight/directory

**Comment by wting** [comment]
Yeah, I'm pretty sure #391 is the culprit. If this happens again and/or you have more info please re-open. Thanks!

**Comment by vlachoudis** [comment]
Thanks
