### ISSUE TITLE
autojump not working with zsh and iterm2

### ISSUE THREAD

**Issue by mbigras** [wting/autojump#421]
Hello there,

I'm using:
zsh with
iTerm 2 Build 3.0.0

After following the post installation notes and adding the following to my `.zshrc`

```
[[ -s /Users/max/.autojump/etc/profile.d/autojump.sh ]] && source /Users/max/.autojump/etc/profile.d/autojump.sh

autoload -U compinit && compinit -u
```

autojump appears to still not be working:

```
autojump git:master ❯ ls
AUTHORS              bin                  tools
CHANGES.md           docs                 tox.ini
LICENSE              install.py           uninstall.py
Makefile             requirements-dev.txt
README.md            tests
autojump git:master ❯ j tools
.
autojump git:master ❯ pwd
/Users/max/repos/autojump
autojump git:master ❯ j help
.
autojump git:master ❯ autojump help
.
```

am I missing something here? Thanks for your help :)

**Comment by bendem** [comment]
From the [readme](https://github.com/wting/autojump#description):

    Directories must be visited first before they can be jumped to.

Also, it's `j --help` to get the help (`man autojump` works too).

**Comment by jonvis23** [comment]
i still dont get it

**Comment by fritx** [comment]
+1 not working with iTerm2+zshrc, while working with MacOS built-in Terminal+zshrc
