### ISSUE TITLE
always return dot

### ISSUE THREAD

**Issue by wangbourne** [wting/autojump#422]
I got all the same result(return dot) when trying autojump or j:

Bournes-MacBook-Pro:firebase BourneWang$ cd ..
Bournes-MacBook-Pro:~ xbox$ j web
.
Bournes-MacBook-Pro:~ xbox$ jc Dropbox
.
Bournes-MacBook-Pro:~ xbox$ 

how can i get this problem done?

**Comment by wting** [comment]
From the [README](https://github.com/wting/autojump#description).

> Directories must be visited first before they can be jumped to.

Also run these commands:

```shell
$ echo $SHELL
$ which j
$ declare -f j
```

**Comment by wangbourne** [comment]
you are right, thanks ,so much :)

**Comment by wting** [comment]
Related to #416.
