### ISSUE TITLE
Is it possible to jump based on parent directory name?

### ISSUE THREAD

**Issue by vineetht** [wting/autojump#424]
Is there any way to jump to a location based on the parent directory. Most times code base will have the same child directory name such as 'src'. In the following case, is there a way to jump to /tmp/temp1/test1?

$ j -s
10.0:	/tmp/temp1/test1
14.1:	/tmp/temp2/test1
28.3:	/tmp
________________________________________

52:	 total key weight
3:	 stored directories
28.28:	 current directory weight
db file: /home/<user>/.local/share/autojump/autojump.txt

$ j temp1
autojump: directory 'temp1' not found
Try `autojump --help` for more information.

Thanks

**Comment by wting** [comment]
Yeah, use multiple arguments as described in the [usage section](https://github.com/wting/autojump#usage). In your case it'd be `j 1 test1` (or `j project src`).

> $ j temp1

The reason this doesn't work is you have to visit a directory before it's stored in the database.
