### ISSUE TITLE
How is `autojump` different from `cdargs`?

### ISSUE THREAD

**Issue by pvdb** [wting/autojump#426]
Not an issue as such, but trying to understand the rationale behing this project a bit better... what sets `autojump` apart from [the venerable `cdargs` Unix utility](http://www.skamphausen.de/cgi-bin/ska/CDargs)?

**Comment by jared-hess** [comment]
From my understanding of cdargs it relies completely on manual configuration. Autojump by default installs a hook into your prompt that allows it to automatically update a database of paths and weights based on what directories you spend time running commands in. This allows ambiguous "needles" passed to autojump to select the most likely directory for you based on how often you use it. 

I'm sure there are other differences but stands out to me as one of the biggest.

**Comment by pvdb** [comment]
Thanks for the clarification, @jared-hess, makes sense... personally, I don't think my workflow would benefit from that kind of functionality, so will stick to `cdargs` for now... may revisit `autojump` at a later stage, though!
