### ISSUE TITLE
Autojump failing 

### ISSUE THREAD

**Issue by marcelolima** [wting/autojump#428]
autojump v22.3.2

When I try to use autojump, it's returning this errror for any 'j' command:

Traceback (most recent call last):
  File "/home/mlima/.autojump/bin/autojump", line 420, in <module>
    sys.exit(main(parse_arguments()))
  File "/home/mlima/.autojump/bin/autojump", line 386, in main
    entries = entriefy(load(config))
  File "/home/mlima/.autojump/bin/autojump_data.py", line 82, in load
    ifilter(correct_length, imap(parse, f))))
  File "/home/mlima/.autojump/bin/autojump_data.py", line 72, in <lambda>
    tupleize = lambda x: (x[1], float(x[0]))
UnicodeEncodeError: 'decimal' codec can't encode character u'\x00' in position 3: invalid decimal Unicode string
autojump: directory '' not found
\n\n

**Comment by wting** [comment]
Doh, that line needs a better debug info / better error handling.

For now the easiest way to fix that is to open `~/.local/share/autojump/autojump.txt` and remove the offending directory entry. If you have multiple Unicode paths, I'd remove all of them.

**Comment by wting** [comment]
^^ that should fix the problem. If you're still having problems please re-open this issue.
