### ISSUE TITLE
jo opens a new console using Terminal.app instead of a new iTerm2 console

### ISSUE THREAD

**Issue by jpcofr** [wting/autojump#431]
jo opens a new console using Terminal.app whenever I call that from a terminal at iTerm2.

I have set my default shell to fishshell and also my default terminal application to iTerm2

**Comment by wting** [comment]
`jo` is just a wrapper around Mac's `open` command. It'll open the path with whatever is the default behavior for a folder.

**Comment by jpcofr** [comment]
Uh thanks. I was aware of that but I do not know why it was opening a new console at the directory given by parameter. (btw it sounds like a good feature to have)

**Comment by wting** [comment]
By default `open` uses Finder for directory links. I confirmed it a few hours ago and again just now (on a new MBP). If it opens in Terminal instead, it means it's a user-local configuration and not an issue related to autojump.

Unfortunately I'm not fluent enough in OSX to help further.
