### ISSUE TITLE
Autojump requires to be sourced although fishshell config.fish is correctly updated

### ISSUE THREAD

**Issue by jpcofr** [wting/autojump#432]
Although I have added the special line to use the autojump with fishshell, I have to source autojump myself after opening a terminal.

**Comment by wting** [comment]
Sounds like an issue with your shell's login script or the fish post-installation message.

**Comment by jpcofr** [comment]
Yeah, as you said, I did not copy the entire line at the post-installation message given I just started to use fishshell the last week. I just copy the entire line, not only the first part. Again thanks for your patience.
