### ISSUE TITLE
sre_constants.error: unterminated character set at position 'x'

### ISSUE THREAD

**Issue by slagernate** [wting/autojump#434]
I downloaded autojump on Windows 7 with Python 3.5.2 but was getting this error:

![image](https://cloud.githubusercontent.com/assets/13192034/17147587/72a92e30-5331-11e6-8d1b-1eecce3bfc26.png)

After looking at autojump_match.py I noticed that os.sep was returning '\' which was escaping the enclosing ']':

    regex_no_sep = '[^' + os.sep + ']*'
    regex_no_sep_end = regex_no_sep + '$'
    regex_one_sep = regex_no_sep + os.sep + regex_no_sep

I got it to work by using this code instead:

    sep = os.sep if os.sep != '\\' else '\\\\'
    regex_no_sep = '[^' + sep + ']*'
    regex_no_sep_end = regex_no_sep + '$'
    regex_one_sep = regex_no_sep + sep + regex_no_sep

**Comment by wting** [comment]
Rolling the Windows crash exceptions into #436.
