### ISSUE TITLE
No directories saved at all in OSX, stats still empty.

### ISSUE THREAD

**Issue by nayefc** [wting/autojump#435]
Running on OSX. I installed autojump using Homebrew a few days ago and my stats are still empty. I realised that the data file that shows up in `j -s` did not exist, so I created it but I'm still getting the same issue.

Do I need to do anything else? I have autojump sourced per the instructions, and the env variable for that shows `1`.

```bash
 $ j -s
________________________________________

0:       total weight
0:       number of entries
0.00:    current directory weight

data:    /Users/mainuser/Library/autojump/autojump.txt
```

Thanks

**Comment by bendem** [comment]
Are you using bash and overriding your PROMPT_COMMAND? Might want to check the [known issues](https://github.com/wting/autojump#known-issues).

**Comment by nayefc** [comment]
Yup that was it. Didn't notice that. Thanks.
