### ISSUE TITLE
Incorrect jump when use zsh on windows' Cygwin

### ISSUE THREAD

**Issue by scottming** [wting/autojump#437]
My jump list:
![list](https://cloud.githubusercontent.com/assets/12830256/17544531/8b68f060-5f0a-11e6-9629-e8dddbd57a2c.png)

.zshrc:
![image](https://cloud.githubusercontent.com/assets/12830256/17544673/43897fe8-5f0b-11e6-8b33-0ccc6a96e887.png)

I want to jump and open the "scottming.github.io" directory, not 'Scott'(`~`). How do I fix it? It always jump there no matter which directory I type.

![jo_zsh](https://cloud.githubusercontent.com/assets/12830256/17544577/c5380f24-5f0a-11e6-9b2d-0aee7df0de30.png)

**Comment by wting** [comment]
`autojump` is a search engine that returns a result in the form of a directory path.

- `jo` takes that result and opens a file browser (different per OS).
- `j` takes the result and "jumps" to it via `cd`

If you want to jump _and_ open a directory then it'd be: `j scottming && jo scottming`

If you do this often, you can shorten it as a shell function:
```bash
jump_and_open() {
    j ${1} && jo ${1}
}
```

**Comment by scottming** [comment]
Thanks, I added the flowing code to my `~/.zshrc` and `.bashrc`, It works.

```bash
jump_and_open() {
    j ${1} && jo ${1}
}

alias jo=jump_and_open
```
