### ISSUE TITLE
slows down zsh startup time considerably

### ISSUE THREAD

**Issue by sodiumjoe** [wting/autojump#443]
First off, thanks for `autojump`!

```bash
➤  /usr/bin/time /bin/zsh -i -c exit
        0.50 real         0.37 user         0.11 sys
```

and with autojump commented out of my `.zshrc`:

```bash
➤  /usr/bin/time /bin/zsh -i -c exit
        0.13 real         0.09 user         0.02 sys
```

most of the time looks like it's spent calling `brew` and `brew --prefix`, so I tried:

`.zshrc`
```bash
# [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
[[ -s /usr/local/etc/profile.d/autojump.sh ]] && . /usr/local/etc/profile.d/autojump.sh
```

and in `/usr/local/share/autojump/autojump.zsh` (which is `$(brew --prefix)/etc/profile.d/autojump.sh`):

```bash
# set homebrew installation paths
# if command -v brew &>/dev/null && [[ -d "$(brew --prefix)/share/zsh/site-functions" ]]; then
#     fpath=("$(brew --prefix)/share/zsh/site-functions" ${fpath})
# fi
if [[ -d "/usr/local/share/zsh/site-functions" ]]; then
    fpath=("/usr/local/share/zsh/site-functions" ${fpath})
fi
```

and now:

```bash
➤  /usr/bin/time /bin/zsh -i -c exit
        0.13 real         0.09 user         0.03 sys
```

seems like you could:
1. set an env var on the first `brew --prefix`
2. let me set the env var myself and skip the `brew --prefix` entirely
3. skip the `command -v brew &>/dev/null` since presumably it's redundant with `brew --prefix`

**Comment by wting** [comment]
Thanks for opening such a detailed issue!

One thing to consider is that micro-benchmarks can be kind of dangerous since single data points have have variance. Here I collect ~10 data points, remove autojump from my `.zshrc`, and then collect ~10 data points.

```shell
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:19 PDT

real	0.68s
user	0.43s
sys	0.21s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:39 PDT

real	0.33s
user	0.23s
sys	0.09s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:40 PDT

real	0.31s
user	0.22s
sys	0.08s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:41 PDT

real	0.31s
user	0.22s
sys	0.08s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:41 PDT

real	0.31s
user	0.22s
sys	0.08s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:42 PDT

real	0.32s
user	0.22s
sys	0.09s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:43 PDT

real	0.32s
user	0.23s
sys	0.09s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:44 PDT

real	0.33s
user	0.23s
sys	0.09s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:41:44 PDT

real	0.34s
user	0.24s
sys	0.09s
╭─@eikyo ~ ‹python-2.7.12›
╰─ # removed autojump                       2016.09.27 15:41:45 PDT
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:07 PDT

real	0.53s
user	0.39s
sys	0.13s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:11 PDT

real	0.29s
user	0.21s
sys	0.07s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:11 PDT

real	0.29s
user	0.21s
sys	0.07s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:12 PDT

real	0.29s
user	0.21s
sys	0.07s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:13 PDT

real	0.29s
user	0.22s
sys	0.07s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:14 PDT

real	0.30s
user	0.22s
sys	0.07s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:15 PDT

real	0.30s
user	0.22s
sys	0.07s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:16 PDT

real	0.29s
user	0.22s
sys	0.07s
╭─@eikyo ~ ‹python-2.7.12›
╰─ time /bin/zsh -i -c exit                 2016.09.27 15:42:16 PDT

real	0.29s
user	0.21s
sys	0.07s
```

If we calculate the 50th percentile and standard deviation (I converted sec to ms):
```python
In [22]: np.median(np.array([680, 330, 310, 310, 320, 320, 340]))
Out[22]: 320.0

In [23]: np.std(np.array([680, 330, 310, 310, 320, 320, 340]))
Out[23]: 125.77920401745793

In [24]: np.median(np.array([530, 290, 290, 290, 300, 300, 290, 290]))
Out[24]: 290.0

In [25]: np.std(np.array([530, 290, 290, 290, 300, 300, 290, 290]))
Out[25]: 78.541390362025041
```

It looks like autojump is adding 30 ms and increased variance (from all the disk seeks). I'm only testing this on SSDs, so the variance on a spinning hdds is probably higher.

>seems like you could:
>1. set an env var on the first brew --prefix

Environment variables aren't persistent between shells.

>2. let me set the env var myself and skip the brew --prefix entirely

This requires manual syncing of the env var and brew installs, and isn't user friendly.

>3. skip the command -v brew &>/dev/null since presumably it's redundant with brew --prefix

This is definitely doable.

At the end of the day loading `autojump.zsh` invokes spawning subshells and disk seeks costing 30 - 370 ms, some of which may or may not be attributed to `brew --prefix`.

I would love to make autojump faster, is there any better evidence that localizes the issue to `brew`?

**Comment by sodiumjoe** [comment]
Hey thanks for the reply!

Before you go on, be warned that i know just enough `zsh` to be dangerous.

> Environment variables aren't persistent between shells.

in `.zshrc` you're using the `.` operator:

```bash
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
```

and in `autojump.sh`, `source`:

```bash
# check global install
elif [ -s /usr/local/share/autojump/autojump.${shell} ]; then
    source /usr/local/share/autojump/autojump.${shell}
fi
```

Some quick googling indicates that `.` and `source` are basically interchangeable, so I'm not sure what your reasons are for using them respectively, but in both cases, it appears they don't spawn a new subshell, so they would have access to any environment variables. I tested this by setting `BREW_PREFIX='/usr/local'` and changing the commands to 

```bash
[[ -s /usr/local/etc/profile.d/autojump.sh ]] && . ${BREW_PREFIX}/etc/profile.d/autojump.sh
```

and

```
# check global install
elif [ -s ${BREW_PREFIX}/share/autojump/autojump.${shell} ]; then
    source ${BREW_PREFIX}/share/autojump/autojump.${shell}
fi
```

and that appears to work fine. You could also put guards in like:

```bash
BREW_PREFIX=$BREW_PREFIX || $(brew --prefix)
```

wherever the env var is referenced.

> This requires manual syncing of the env var and brew installs, and isn't user friendly.

agreed, but it would be nice to have the option to set it directly instead of running `brew --prefix`, and if the installer just set `BREW_PREFIX=$(brew --prefix)` in `.zshrc`, i could just change it myself.

>  is there any better evidence that localizes the issue to brew

best i can do is:

```bash
➤  /usr/bin/time brew --prefix`
```
consistently takes about .1ms

while
```bash
➤  /usr/bin/time brew
```
consistently takes about .45ms

If you have any ideas about how to prove that out further, I'd be happy to do the legwork.

**Comment by wting** [comment]
>>Environment variables aren't persistent between shells.

>in .zshrc you're using the . operator:

If you save `brew --prefix` to an env var, you have to set it again when opening a new terminal (new shell) eliminating any performance differences.

>so I'm not sure what your reasons are for using them respectively, but in both cases, it appears they don't spawn a new subshell,

Calling the results of the function using two backticks or `$()` creates a subshell, which is a fork of the current shell and has associated overhead from copying address space into the new child process.

```bash
# check global install
elif [ -s ${BREW_PREFIX}/share/autojump/autojump.${shell} ]; then
    source ${BREW_PREFIX}/share/autojump/autojump.${shell}
fi
```
>and that appears to work fine. You could also put guards in like:

It looks like you're using an old version of autojump; that code was removed for [security reasons](http://www.openwall.com/lists/oss-security/2013/04/25/13). Can you please reproduce these performance results with the version from GitHub (v22.3.5)?

**Comment by sodiumjoe** [comment]
> Can you please reproduce these performance results with the version from GitHub (v22.3.5)?

I was on the latest `autojump` from `brew`, which reported it as that version:

```bash
 ~ ➤  brew info autojump
autojump: stable 22.3.5 (bottled), HEAD
```

but I just installed manually and everything is much faster now! (looks like you removed `brew --prefix) from the `.zshrc` snippet)

now my zsh startup time averages around:

```bash
➤  /usr/bin/time /bin/zsh -i -c exit
        0.18 real         0.12 user         0.06 sys
```

changing `~/.autojump/share/autojump/autojump.zsh` to

```bash
local brew_prefix=$(brew --prefix)
if [[ -d "${brew_prefix}/share/zsh/site-functions" ]]; then
    fpath=("${brew_prefix}/share/zsh/site-functions" ${fpath})
fi
```
cuts out one `brew --prefix` call and shaves a around .03ms

changing it to:

```bash
local brew_prefix=${BREW_PREFIX:-$(brew --prefix)}
if [[ -d "${brew_prefix}/share/zsh/site-functions" ]]; then
    fpath=("${brew_prefix}/share/zsh/site-functions" ${fpath})
fi
```

and setting `BREW_PREFIX` myself in `.zshrc` shaves it another .03ms, while leaving the operation the same if `BREW_PREFIX` is unset.

Would you accept that in a PR?

**Comment by wting** [comment]
>local brew_prefix=${BREW_PREFIX:-$(brew --prefix)}

lol that's some fancy paremater expansion.

Yeah I'd love a PR! BTW thanks for doing the legwork on this and investigating.
