### ISSUE TITLE
XDG on all unix platforms

### ISSUE THREAD

**Issue by danielb2** [wting/autojump#447]
Is it possible for me to configure autojump to use XDG configuration on all platforms, specifically OSX. It seems OSX is using `~/Library/autojump`

But I would like it to use `~/.config/autojump`

**Comment by wting** [comment]
Unfortunately OSX doesn't support XDG spec and it's preferred to use the OSX's equivalents.

**Comment by danielb2** [comment]
What do you mean? Fishshell manages to use `~/.config/fish` just fine.   neovim uses ~/.config/nvim` just fine.  autojump can't ?

**Comment by wting** [comment]
It's not a matter of can you do it, but rather should you do it.

XDG is a standard for freedesktop.org projects, which includes GNOME, KDE, XFCE, etc. It is a Linux thing, not a BSD or OSX thing.

Using XDG spec on OSX is like creating a "My Documents" folder on a Linux distro.

**Comment by danielb2** [comment]
Freedesktop is an X windows thing, and X windows is not limited to Linux. It's a UNIX thing. It may not be a OSX thing, but OSX is part of the UNIX thing. 

Anyway, I don't care enough. It's just odd since them majority of commandline tools (I'm guessting 99%) follow a convention of using ~/.dotfiles of some form or another to store config files.

**Comment by Hund** [comment]
I'm the opposite boat. I'm using LInux and I don't want to install xdg-utils which will pull about 50 packages for me on my window manager only desktop.

What options do I have?

**Comment by danielb2** [comment]
@hund my proposal is only to put config files in the xdg style since it doesn't pollute the home directory with hidden files. It has nothing to do with installing anything more

**Comment by Hund** [comment]
@danielb2 Your issue is that you want to use xdg-utils, my issue iis that I don't want to use it since i don't have a desktop environment.

Using something else would be pretty easy if we actually had a configuration file.

**Comment by danielb2** [comment]
@Hund Believe it or not, I know exactly what I was suggesting.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

All I was suggesting is to use this convention which more and more new apps are following (neovim, fishshell, etc)

**Comment by danielb2** [comment]
> Using XDG spec on OSX is like creating a "My Documents" folder on a Linux distro.

Not at all. Many programs use `$HOME/.rc`  convention and there's nothing wrong with doing that, just as there is nothing wrong with using `$HOME/nvim/init.vim`

**Comment by Hund** [comment]
@danielb2 Oh, sorry. I totally misunderstood your issue. I'm sorry! The issue I'm having is that autojump is currently half-broken for me since I don't want to use xdg-open from xdg-utils:

```
$ jo hdd0
jo:11: command not found: xdg-open
```

I thought you wanted to use xdg-open from xdg-utils but couldn't. I guess I was pretty tired when I read it.

**Comment by danielb2** [comment]
@Hund  I think maybe the original title was misleading. no worries
