### ISSUE TITLE
zsh: command not found: f

### ISSUE THREAD

**Issue by chiuan** [wting/autojump#459]
my new macbook pro and use brew install zsh & set the default shell to zsh.
and then brew install autojump
and i have see the steps to setup already.
autojump is ok,but f not working!?

zsh 5.2
autojump v22.5.0
homebrew 1.1.2

i dont know how to fix this...i have try my best. please help.

**Comment by bendem** [comment]
The command is `j`, not `f`. If you set up an alias on your previous config, you'll have to do it again (`echo "alias f=j" >> ~/.zshrc`).
