### ISSUE TITLE
Unclear how to properly install under Gentoo

### ISSUE THREAD

**Issue by markasoftware** [wting/autojump#469]
Running `emerge autojump` properly installs autojump, but when running `autojump` it says "please source the correct autojump file in your shell's startup file." etc etc. It says to read te post installation instructions, but there are none that are shown after emerging or in the readme.

**Comment by xr09** [comment]
Add `source /path/to/autojump.sh` to your bashrc, then use it with j.

**Comment by bendem** [comment]
From the [wiki](https://github.com/wting/autojump/wiki#installation)

> Manual installation of autojump is very simple: copy autojump to /usr/bin, autojump.sh to /etc/profile.d, and autojump.1 to /usr/share/man/man1. Make sure you source the appropriate file in your .bashrc:
> ```sh
> source /etc/profile.d/autojump.sh
> ```

**Comment by markasoftware** [comment]
Thanks for the wiki link, didn't see that.
