### ISSUE TITLE
command not found: d 

### ISSUE THREAD

**Issue by hanLovestone** [wting/autojump#471]
Hi, I can use command "d" to show a list of which every line starts with a number from 0 to 9, I can type the number to enter the dir.
However it only works on my MacBook Pro and when I use it on CentOS, Ubuntu or iMac, I receive only the "command not found: d ".
"j"  works correctly.

How can I fix it? 
Thanks!

**Comment by wting** [comment]
`d` is not a command provided by autojump, a built-in bash or zsh command, or a default command for OSX or Ubuntu. I'm not sure which program provides it, but running the following command on your laptop should provide more info:

```shell
$ which d
$ cat $(which d)
```
