### ISSUE TITLE
Parse errors after updating zsh

### ISSUE THREAD

**Issue by nickmccurdy** [wting/autojump#494]
I installed both autojump and zsh through homebrew. Today I upgraded zsh and I'm getting parse errors from autojump on every new shell, though the `j` command appears to work.

## Versions
- zsh 5.4.1
- autojump 22.5.1

## Output
```
/usr/local/share/autojump/autojump.zsh:85: defining function based on alias `jo'
/usr/local/share/autojump/autojump.zsh:85: parse error near `()'
/usr/local/Cellar/autojump/22.5.1/share/autojump/autojump.zsh:85: defining function based on alias `jo'
/usr/local/Cellar/autojump/22.5.1/share/autojump/autojump.zsh:85: parse error near `()'
```

**Comment by ndrone** [comment]
Received the same this morning as well.

**Comment by Hund** [comment]
Not sure if I should create my own ticket, my I'm having similar issues on one of my Arch Linux computers running the exakt same config as the others.

```
$ source ~/.zshrc
/usr/share/autojump/autojump.zsh:49: defining function based on alias `j'
/usr/share/autojump/autojump.zsh:49: parse error near `()'
```

I've tried both with version `22.5` from the community-repo and currently latest code from git (`22.5.1.r12.gb06d686`).

**Comment by ndrone** [comment]
found if I removed the `alias j="j"` from the `.zshrc` file. Removes this parsing error

**Comment by wting** [comment]
I'm glad it worked out for you.

I'm not involved in the Homebrew installation (`alias j="j"` should never happen), but it looks like the issue's been resolved as of today.

**Comment by end-zht** [comment]
```
/usr/share/autojump/autojump.zsh:49: defining function based on alias `zz'
/usr/share/autojump/autojump.zsh:49: parse error near `()'
```
* I do not know why this problem appears, the same file in one machine is no problem, but in another machine is so wrong

**Comment by bep** [comment]
Got this on a very fresh install today:

```bash
➜  ~ source .zshrc
/usr/local/share/autojump/autojump.zsh:49: defining function based on alias `j'
/usr/local/share/autojump/autojump.zsh:49: parse error near `()'
/usr/local/Cellar/autojump/22.5.3/share/autojump/autojump.zsh:49: defining function based on alias `j'
/usr/local/Cellar/autojump/22.5.3/share/autojump/autojump.zsh:49: parse error near `()'


```

**Comment by kelveden** [comment]
@bep I had the same problem on MacOS and found that it was because of a clash with an existing alias of `j` to `z` - which itself was broken as `z` didn't exist. So I just did `unalias j` and the sourcing then worked.

(I did briefly dig around for where the alias was defined but didn't find it.)

**Comment by fredleger** [comment]
hiting the same because i followed the documention of fasd in the past which seems to be unused now

**Comment by wangjinjie722** [comment]
same here in zsh ubuntu18.04

**Comment by bestdax** [comment]
I had the same trouble. It's caused by alias conflicts. 
In terminal, use command `alias` you can find there is a setting `j=zz`.
`zsh -ixc : 2>&1 | grep j=zz` or `bash -ixlc : 2>&1 | grep j=zz` will show the definition of this alias. In my case, this is caused by `fasd` plugin. After uninstall `fasd` it returns back to peace.
