### ISSUE TITLE
Open finder windows in NEW WINDOW

### ISSUE THREAD

**Issue by zsiegel92** [wting/autojump#496]
Hey there,

Would it be possible to use autojump's `jo` (or even the standard OS X `open`) to ALWAYS open a new window?

That is, when I press `jo <directory>`, I would like to open a new finder window at that directory, regardless of whether I already have a finder window open at that directory. Currently, if I have another finder window open at that directory (on ANY of my desktops!), `jo <directory>` just switches finder focus to that window. Given my desktop/spaces preferences, this doesn't actually make that window visible to me.

I would like for `jo` to always open a new window, no matter what else is open. I notice that the standard OS X `open` has the same behavior, and `jo` probably just calls `open`. So, this may be an issue worth solving outside of autojump.

Thank you!

**Comment by wting** [comment]
`jo` just calls `open`, but `open` cannot open a new window every time based on Googling and manual testing (at least for OS 10.13.6):

```shell
╭─@ringo ~ ‹python-2.7.10›
╰─ open /                                                                                                                                                                                                      127 ↵ 2018.09.06 18:40:00 PDT
╭─@ringo ~ ‹python-2.7.10›
╰─ open /                                                                                                                                                                                                            2018.09.06 18:40:02 PDT
╭─@ringo ~ ‹python-2.7.10›
╰─ open /                                                                                                                                                                                                            2018.09.06 18:40:07 PDT
```

If you know how to open a new window every time via `open` then please feel free to share it here.
