### ISSUE TITLE
some database entries lost after using some time

### ISSUE THREAD

**Issue by tanglianggithub** [wting/autojump#500]
entries once were in the database, that is to say, can see that directory using autojump -s.
after some time, cannot find that directory.

found issue: https://github.com/wting/autojump/issues/391
but didn't find a solution.

autojump v22.5.1
CentOS release 6.8

**Comment by brandonwanggit** [comment]
i have the same problem, too.
i hacked some codes in the autojum_data.py to backup the autojump.txt in a small interval.
after losing the autojump.txt, i can recover the autojump.txt manually.

**Comment by wting** [comment]
Dupe of #391.
