### ISSUE TITLE
Add by default file manager bookmarks

### ISSUE THREAD

**Issue by pabloab** [wting/autojump#502]
This is a enhancement suggestion: Would be great if autojump offer out-of-the-box what the user have already on their file manager bookmarks. For example to do this with Nautilus in Linux would be something like:

    grep -oP "(?<=file://)$HOME.*$" ~/.config/gtk-3.0/bookmarks | col1 | sed "s/%20/ /g" | xargs -I path bash -c 'cd "path" && pwd && autojump --add "$(pwd)"'

**Comment by wting** [comment]
Sounds like you already have an answer for yourself. :stuck_out_tongue: 

While it's a good idea, it's difficult to support different file managers on different OS'es.
