### ISSUE TITLE
Read from/Write to wrong database file

### ISSUE THREAD

**Issue by tigerjack** [wting/autojump#504]
I'm using `autojump v22.5.1` on `Arch Linux`. Today I noticed a strange behavior.
My database file was usually stored at `$HOME/.local/share/autojump/autojump.txt`. However, now it tries to read the entries from the file `$HOME/.local/share/autojump.txt` and obviously it doesn't find any entry.

I don't know if it's related, but yesterday I exported the `$XDG_DATA_HOME` to `$HOME/.local/share`. Maybe when this is set, `autojump` automatically tries to read/write the database file to `$XDG_DATA_HOME/autojump.txt` instead of the default `$XDG_DATA_HOME/autojump/autojump.txt`? Is it possible to change this behavior?

**Comment by wting** [comment]
Thanks for the bug report.

I've fixed this in https://github.com/wting/autojump/commit/6a529f4f929042a37e7394d8c91ba31b479189a2. Let me test this locally for a while before cutting a release.
