### ISSUE TITLE
what can i do for this problem?

### ISSUE THREAD

**Issue by lovezeropython** [wting/autojump#519]
/root/.autojump/share/autojump/autojump.zsh:22: command not found: uname
/usr/share/autojump/autojump.zsh:13: command not found: uname
/usr/libexec/grepconf.sh:行5: grep: 未找到命令
/root/.oh-my-zsh/oh-my-zsh.sh:3: command not found: env
env_default:1: command not found: env
env_default:1: command not found: grep
env_default:1: command not found: env
env_default:1: command not found: grep
/root/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/root/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
/root/.autojump/share/autojump/autojump.zsh:22: command not found: uname
/root/.zshrc:81: compinit: function definition file not found

**Comment by wting** [comment]
You have issues with your zsh setup that's more than just autojump. Looks like common apps (`uname`, `env`, `grep`, etc) aren't in your `$PATH`.
