### ISSUE TITLE
Clean database

### ISSUE THREAD

**Issue by wbhob** [wting/autojump#520]
Hello,
I have an issue where running `j ~` simply jumps to the first folder I ever `j`'d into with autojump. I have tried uninstalling it, but even after reinstalling, the issue persists. Can I get some support on this?

Terminal: iTerm2
Prompt: Zsh
OS: macOS Sierra

**Comment by cipri-tom** [comment]
You can inspect the database with `j -s` and "clean" it by removing the file which hosts it (indicated on the last line in `j -s`)

**Comment by wbhob** [comment]
Ok, but how can I link /Users/myusername to `j ~`

**Comment by cipri-tom** [comment]
I don't think that is possible. Autojump is not a replacement for `cd`, it is an augmentation of it.

That being said, note that `j ~` has three chars, whereas `cd` has only 2 😉 and `cd` without arguments will take you to your home directory.

**Comment by wbhob** [comment]
ok, this helps a lot. thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
