### ISSUE TITLE
jump can't find the right path directly

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [wting/autojump#525]
I installed autojump on Ubuntu 16.04 LTS,put  . /usr/share/autojump/autojump.sh  into the .bashrc. After source the .bashrc file,I get this situation:
$ cd Desktop/
$ cd ..
$ j D__
D__1__/home/moon/Desktop    D__2__/home/moon/Desktop

I used tab key.
@nicoulaj @KenMacD @blueyed @junkblocker @marktran

**Comment by Karmaki** [comment]
I think that is a duplicate of #348.

**Comment by wting** [comment]
Closing as dupe of #348.
