### ISSUE TITLE
command not found: autojump

### ISSUE THREAD

**Issue by lzr900515** [wting/autojump#529]
1. use: brew install autojump 
`
➜  ~ mdfind -name 'autojump.sh'
`
**result: /usr/local/Cellar/autojump/22.5.1/etc/profile.d/autojump.sh**

2. and vim ~/.zshrc to change the config like below:
`
plugins=(git autojump)
[[ -s $(brew --prefix)/Cellar/autojump/22.5.1/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/Cellar/autojump/22.5.1/etc/profile.d/autojump.sh
source $ZSH/oh-my-zsh.sh
`
3. then use j : 
`
➜  ~ j
`
**result:
j:7: command not found: autojump
autojump: directory '' not found
Try `autojump --help` for more information.**

4. use autojump:
`
➜  ~ autojump
`
**result:
zsh: command not found: autojump**

how to solve this problem? thanks

**Comment by lelewolf** [comment]
restart Terminal

**Comment by lzr900515** [comment]
one document have no writable authority。 brew link step goes error. have solve it.
