### ISSUE TITLE
Problem with jumping to the same prefix folder

### ISSUE THREAD

**Issue by TimSnake13** [wting/autojump#533]
I have a folder named "OS" (usr/work/OS) and the other named "OS_Project" (usr/work/OS_Project).
When I try to use "j OS", it will automatically jump to "OS_Project".
Is there any way to actually to jump to my "OS" folder instead of the others?

**Comment by TimSnake13** [comment]
BTW, I am using macOS.

**Comment by cipri-tom** [comment]
Yeap, there are 2 ways (at least) to accomplish that.

If you just executed `j OS` and it jumped to `OS_Project` then you can just rerun the same command again (arrow up, enter) and it will jump to the next directory on the list, supposedly the `OS` one.

Alternatively, you can decrease the weight of the `OS_Project` directory (see `j -h`). You can inspect the weights using `j -s`. There will be a list of all directories as well as `current directory weight`. So run `j -d <amount>` in the `OS_Project` with an `<amount>` that will bring its weight below the other one.
