### ISSUE TITLE
how to totally uninstall autojump

### ISSUE THREAD

**Issue by kingname** [wting/autojump#537]
I have already uninstall autojump by the command `sudo apt-get remove autojump`

however, when I cd to any folder, the terminal will raise error: 

```
autojump_chpwd:4: nice(5) failed: operation not permitted
autojump_chpwd:4: command not found: autojump
```

**Comment by tjtaylo** [comment]
I'm having the same issue. Has anyone found a solution?

**Comment by wting** [comment]
Autojump is have binary and have shell script. Removing the Debian package only removes the binary.

Please go into `~/.zshrc` and remove anything referencing autojump in there and restart your terminal.

**Comment by tjtaylo** [comment]
@wting That worked for me, thank you!!

**Comment by azzamsa** [comment]
Having the some problem. Removed everything under `bashrc/profile`, but the issue persists.

The warning gone after reboot.
