### ISSUE TITLE
/root/.autojump/share/autojump/autojump.zsh: line 44: typeset: -U: invalid option

### ISSUE THREAD

**Issue by lcyan** [wting/autojump#538]
++ typeset -gaU chpwd_functions
/root/.autojump/share/autojump/autojump.zsh: line 44: typeset: -U: invalid option
typeset: usage: typeset [-aAfFgilrtux] [-p] name[=value] ...
++ chpwd_functions+=autojump_chpwd

**Comment by wting** [comment]
Are you trying to source the zsh file from a bash shell?

What happens when you [install from source](https://github.com/wting/autojump#manual)?
