### ISSUE TITLE
jc does not work as intended on mac

### ISSUE THREAD

**Issue by dhruvkapur91** [wting/autojump#541]
Hi, I'm using OS X, High Serria.

And `autojump 22.5.1` and `/bin/zsh` as shell

The command `j` works like a charm, however the command `jc` which I think should navigate locally does not do as intended. How can I look more into the issue or resolve it?

**Comment by wting** [comment]
Seems to work for me:

```shell
╭─@ringo ~ ‹python-2.7.10›
╰─ mkdir -vp ~/foo/bar                                                                       2018.09.05 22:25:25 PDT
╭─@ringo ~ ‹python-2.7.10›
╰─ cd ~/foo/bar                                                                              2018.09.05 22:25:31 PDT
╭─@ringo ~/foo/bar ‹python-2.7.10›
╰─ ..                                                                                        2018.09.05 22:25:39 PDT
╭─@ringo ~/foo ‹python-2.7.10›
╰─ jc bar                                                                                    2018.09.05 22:25:40 PDT
/Users/ting/foo/bar
╭─@ringo ~/foo/bar ‹python-2.7.10›
╰─ j -v                                                                                      2018.09.05 22:25:44 PDT
autojump v22.5.1
╭─@ringo ~/foo/bar ‹python-2.7.10›
╰─                                                                                           2018.09.05 22:25:57 PDT
```

Keep in mind that you can only jump to directories you've previously visited. What happens when you use `jc` and it doesn't work as expected?

**Comment by idoo** [comment]
I can confirm, jc doesn't work for me as well

it works well in the example above, but doesn't in the directory that I navigated by `j`

**Comment by wting** [comment]
@idoo: Can you duplicate the exact steps in the above shell log and share the results here?

**Comment by idoo** [comment]
```
 ~ cd My\ Folder/
 ~/My Folder ls
Some Name
 ~/My Folder  jc Name
 ~/My Folder
```

**Comment by wting** [comment]
Have you visited "Some Name" before? autojump will jump to directories that you haven't visited before.

**Comment by idoo** [comment]
@wting yes, it's reason of this issue, please close that issue
