### ISSUE TITLE
wrong autojump.fish config file in repo of ubuntu16.04

### ISSUE THREAD

**Issue by Charles-Neil** [wting/autojump#542]
OS: ubuntu 16.04
autojump: v22.2.4

When I was trying out this awesome tool I found that the command `jo` always failed. Then I looked into the `/usr/share/autojump/autojump.fish` script file and found the following code missing a `not`: 

```
# line number: 71
# open autojump results in file browser
function jo
    set -l output (autojump $argv)
    ########### should be `if not test -d "$output"`##########
    if test -d "$output"
        __aj_err "autojump: directory '"$argv"' not found"
        __aj_err "\n$output\n"
        __aj_err "Try `autojump --help` for more information."
    else
        switch (sh -c 'echo ${OSTYPE}')
            case 'linux*'
                xdg-open (autojump $argv)
            case 'darwin*'
                open (autojump $argv)
            case cygwin
                cygstart "" (cygpath -w -a (pwd))
            case '*'
                __aj_error "Unknown operating system: '"$OSTYPE"'"
        end
        echo end
    end
end
```

After I added the missing `not` it worked fine.
I installed autojump by apt: `apt install autojump` and source the autojump.fish in the fish config file`~/.config/fish/config.fish`

**Comment by wting** [comment]
Debian tends to be pretty far behind. Can you [install from source](https://github.com/wting/autojump#manual) and reproduce the issue?

**Comment by Charles-Neil** [comment]
Nope, cannot reproduce the issue after install from source.

**Comment by wting** [comment]
Thanks for letting me know!
