### ISSUE TITLE
When I re-login my vps,the record has been cleaned.

### ISSUE THREAD

**Issue by Akemi-Homura** [wting/autojump#545]
![image](https://user-images.githubusercontent.com/16780053/46208835-95100f80-c35e-11e8-8fc7-4bb48ff4e4d0.png)
I use autojump on archlinux with zsh and config `.zshrc` as below
![image](https://user-images.githubusercontent.com/16780053/46208873-bd980980-c35e-11e8-8f8e-244124eaf934.png)

**Comment by wting** [comment]
Hmm if you check the data file it should be non-zero. If it's being truncated or recreated every time you login then it's probably an environment issue that's not related to autojump.

**Comment by Akemi-Homura** [comment]
@wting emmm.But how to fix it ?

**Comment by Akemi-Homura** [comment]
@wting  I tried re-install `autojump` manually and it runs normally. Thank you!
