### ISSUE TITLE
Autojump and (Intel) miniconda

### ISSUE THREAD

**Issue by Sbozzolo** [wting/autojump#547]
I have a workstation with Gentoo and autojump installed from the official repos. I use that machine mostly for scientific computing, so I find convenient to use Intel distribution of Python installed with miniconda. This brakes autojump: every time I visit a folder I would get an error complaining that the module `autojump` cannot be found. I verified that the distribution of Python is the culprit by forcing autojump to use my system Python in `/usr/bin`, and resulting in all the error disappearing and all the software working as expected.

**Comment by wting** [comment]
I would edit autojump and hardcode it to always use the system's Python. You can do it like so:

```shell
$ vim $(which autojump)
- #!/usr/bin/env python
+ #!/usr/bin/python
```

I won't change this at the package level because Python installation are different paths and versions on every system.

**Comment by Sbozzolo** [comment]
This is exactly what I did. I reported here hoping that this could be
solved upstream by other means.
