### ISSUE TITLE
jc is not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by gpenghe** [wting/autojump#549]
First thanks for the awesome tool. I've been using it all the time in the last few months and the time it saves and the convenience it offers are tremendous.

The only problem is the `jc` seems is not working a lot of time. Just do a quick simple example: (the last `jc` result is wrong):

```Shell
$ mkdir jctest
$ cd jctest/
$ mkdir -p a/b/c/d/foo
$ mkdir -p a2/b2/c2/d2/foo
$ cd a/b/c/d/foo/
$ cd -
/home/xxx/jctest
$ cd a2/b2/c2/d2/foo/
$ cd -
/home/xxx/jctest
$ cd a2
$ jc foo
/home/xxx/jctest/a2/b2/c2/d2/foo
$ cd -
/home/xxx/jctest/a2
$ j foo
/home/xxx/jctest/a2/b2/c2/d2/foo
$ cd -
/home/xxx/jctest/a2
$ cd ../a
$ jc foo
/home/xxx/jctest/a2/b2/c2/d2/foo

```

The version tested is the current latest version of 06e082c. I am using Ubuntu 16.04. I installed `autojump` through git repo and did a `./install.py`.

**Comment by cpmsmith** [comment]
#444 fixes this.

**Comment by keai4le** [comment]
I found this issue too.
46.9: /home/my/project1/foo/bar/target
187.6: /home/my/project2/foo/bar/target

Then, using "jc target" at /home/my/project1, it will jump to "/home/my/project2/foo/bar/target"
autojump v22.5.0

**Comment by gpenghe** [comment]
> #444 fixes this.

It doesn't.  Just tried @keai4le's example, still not working as of the current HEAD (v22.5.3).

**Comment by gpenghe** [comment]
> I found this issue too.
> 46.9: /home/my/project1/foo/bar/target
> 187.6: /home/my/project2/foo/bar/target
> 
> Then, using "jc target" at /home/my/project1, it will jump to "/home/my/project2/foo/bar/target"
> autojump v22.5.0

#444 indeed fixed this but is not merged yet.  I just tried https://github.com/cpmsmith/autojump and it worked.
