### ISSUE TITLE
Surprisingly large score

### ISSUE THREAD

**Issue by lilydjwg** [wting/autojump#566]
Hi, I don't think I can reproduce this, but report here anyway to let you know. While debugging why my automount is triggered, I find that a now-non-existent path on my automount point has a surprisingly large score: 776601683796.0. This is a very old path and I didn't visit it much when it existed.

(I've manually removed this entry and autojump no longer unnecessarily visits my automount point :+1:)

**Comment by wting** [comment]
Hmm, autojump works by using shell hooks to detect when a directory has been visited and increments that entry.

If you're running command line actions that changes the working directory often or regularly then it'll trigger the hook and increment the automount path.

While I can't think of an improvement for the working directory hook, this does seem like more of an argument for an ignore list to block certain paths.

**Comment by lilydjwg** [comment]
It's rather unlikely that it was caused by a script. Even the score increases linearly, assuming one run of such a script changing cwd takes 10ms, it would take 776601683796 / 10 * 0.1 / 86400 / 365 ≈ 246 years to gain such a high score.

Actually the score jumped from `31.622776601683796` to `776601683796.0` recently, according to my backups. I've lost about 800 entries during that period (12days) too (file size from 157K to 117K).

**Comment by lilydjwg** [comment]
This might have the same cause as #391 and I've checked that my `autojump_data.py` indeed didn't contain the fix when this happened. (I applied the fix for some time but then an update from the OS overrode the fix during that time.)

**Comment by wting** [comment]
Thanks for following up and lemme know if that doesn't fix the issue!
