### ISSUE TITLE
Command not found: j

### ISSUE THREAD

**Issue by qazip** [wting/autojump#569]
I am using antergos and installed autojump with pacman. I have already restarted the terminal but I am still getting the message:

`zsh: command not found: j`

I am missing a source in my zshrc, but I cannot find any info regarding that in the README. Shouldn't I source an .sh or something?

**Comment by qazip** [comment]
I suggest adding the following to the README:

`source /usr/share/autojump/autojump.zsh`

**Comment by wenJonSnow** [comment]
me too

**Comment by CasperMoo** [comment]
> I suggest adding the following to the README:
> 
> `source /usr/share/autojump/autojump.zsh`

then It says: "source: no such file or directory: /usr/share/autojump/autojump.zsh"
(using osx, installed autojump with brew.)

**Comment by CasperMoo** [comment]
> I suggest adding the following to the README:
> 
> `source /usr/share/autojump/autojump.zsh`

that works for me.
but for me,  the path is '/usr/local/Cellar/autojump/22.5.3/share/autojump/autojump.zsh'.

**Comment by sundarv85** [comment]
> but for me, the path is '/usr/local/Cellar/autojump/22.5.3/share/autojump/autojump.zsh'.

When you come from brew, as noted at the end of the installation, you have to do the following

```
Add the following line to your ~/.bash_profile or ~/.zshrc file:
  [ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

If you use the Fish shell then add the following line to your ~/.config/fish/config.fish:
  [ -f /opt/homebrew/share/autojump/autojump.fish ]; and source /opt/homebrew/share/autojump/autojump.fish

Restart your terminal for the settings to take effect.
```

**Comment by HassanMahmud** [comment]
Ran into this and missed the postinstall message - could be nice if it was in the readme.
