### ISSUE TITLE
Error while installation on mac

### ISSUE THREAD

**Issue by viggy28** [wting/autojump#573]
First of all, if its already been address, I am sorry for creating another issue.

Tried with brew and manual installation both leading to same issue.

After manual installation, I got the message **[[ -s /Users/vignesh.ravichandran/.autojump/etc/profile.d/autojump.sh ]] && source /Users/vignesh.ravichandran/.autojump/etc/profile.d/autojump.sh**

I added to ~/.bash_profile.

After restart, I am getting _-bash: /Users/vignesh.ravichandran/.autojump/etc/profile.d/autojump.sh: line 27: syntax error: unexpected end of file_

In fact, i was able to install successfully on my another Mac. It makes me to think something wrong with my machine. Can someone help? TIA.

**Comment by omi10859** [comment]
After installing using brew it just saying no command `j`

**Comment by viggy28** [comment]
For the sake of completeness. 

Had a discussion in SO. 
https://stackoverflow.com/questions/55720897/unable-to-source-a-simple-bash-script/55765233#55765233
