### ISSUE TITLE
in Macos, type command "j" or "jc" to a directory and the zsh just print "." and never enter the corresponding directory

### ISSUE THREAD

**Issue by johnsoncheg** [wting/autojump#578]

**Comment by xbear23** [comment]
same

**Comment by gary-ruizhang** [comment]
Duplicate of #554 
You need to cd to the directory without autojump first. Seems like autojump will keep a record of all the directory you had entered and use this to jump. And after you cd to a directory. All the parent directory will also in that record.

**Comment by johnsoncheg** [comment]
@gary-ruizhang got it.
