### ISSUE TITLE
 python>=3.8 (Wanted by: autojump)

### ISSUE THREAD

**Issue by JackDinn** [wting/autojump#594]
Sorry for my ignorance but iv been using autojump for a couple of years but today it tried to update but has the following error 
```
❰greg❙~❱✔≻ yay -Syu
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: fontconfig: local (2:2.13.1+12+g5f5ec56-2) is newer than extra (2:2.13.1+12+g5f5ec56-1)
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> fontconfig: local (2:2.13.1+12+g5f5ec56-2) is newer than extra (2:2.13.1+12+g5f5ec56-1)
:: 1 Packages to upgrade.
1  aur/autojump  22.5.3-4 -> 22.5.3-5
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
==> Error: Could not find all required packages:
    python>=3.8 (Wanted by: autojump)
```
I do not see a python 3.8 because 3.7.4-2 is the latest for Manjaro (Arch)?
```
❰greg❙~❱✔≻ yay -Si python
Repository      : extra
Name            : python
Version         : 3.7.4-2
```

**Comment by graysky2** [comment]
@JackDinn - See my comments in https://github.com/wting/autojump/issues/593 ... this is not an issue related to upstream.  It is that Manjaro != Arch Linux.  Your python version is behind Arch's python version.

You can change the `depends=` and the `_python=` in the PKGBUILD to `python3.7` and rebuild and it should work for you.

**Comment by JackDinn** [comment]
Thx but i have tried to edit the PKGBUILD before, i failed to figure it then and i cant figure it now either. I gave up letting linux frustrate me to the point of losing my hair ages ago now.

Thx for the help though.

**Comment by Syphdias** [comment]
@JackDinn try the `autojump-git` package

**Comment by JackDinn** [comment]
> @JackDinn try the `autojump-git` package

well i was just going to leave it in the IgnorePkg in /etc/pacman.conf until Manjaro gets a python update but the -git version is working just fine , Thx :)

**Comment by Syphdias** [comment]
@graysky2 Pinning it to a specific python version seems a bit arbitrary. Won't the package break with the next python release even for pure arch users? (No idea if the installed packages will be automatically migrated with the python upgrade)
Isn't there a way to use the latest available python version? (Rhethorical question, the question is, if you are open to implementing it :wink:)

PS: This is not the place to discuss this imo since this is purely AUR package related. I'll open an issue on the AUR

**Comment by JackDinn** [comment]
That did not last long , the autojump-git is now saying the same thing (python>=3.8 (Wanted by: autojump)
So Iv just uninstalled. I shall wait until Manjaro updates python.

**Comment by graysky2** [comment]
@Syphdias - If you know of a better place to put these let me know.
@JackDinn - Just edit the PKGBUILD as I described.

**Comment by JackDinn** [comment]
@graysky2  yea but as i described i dont know how?
Iv seen yay -G which downloads PKGBUILD, i can edit it but dont know what to do with it after that.
Iv seen --editmenu option for yay but i cant figure how to use it ? yay -S autojump --editmenu or yay -S --editmenu autojump ?
I just want an option/switch i can use to tell yay that i want to edit the PKGBUILD just this once before it installs autojump but i cant figure it.

**Comment by graysky2** [comment]
@JackDinn - Remove yay.  Browse to the AUR, search for the package, download the package, untar the package, edit the `PKGBUILD` making the modifications I mentioned.  Build with `makepkg -srci`

**Comment by JackDinn** [comment]
hmm, Ok im with you, thx. 
Just curious, what if i did this?

  ```
  yay -G <package_name>
  edit the PKGBUILD
  makepkg -srci
```

**Comment by graysky2** [comment]
I assume the -G switch downloads from the AUR?  I do not use that software.

**Comment by JackDinn** [comment]
aye "(Get PKGBUILD from ABS or AUR)"

> Remove yay. Learn Arch without the silly helpers. It is not hard and will save you headaches

You sure it wont be the cause of headaches ^^ , linux is like swimming through treacle but i persevere because i hate M$ and windows 10 (especially) so much.  I might take a look some time but i am just to busy atm.
