### ISSUE TITLE
Please consider changing license

### ISSUE THREAD

**Issue by yehya** [wting/autojump#607]
I can't use this at work due to the license. Just a shame it looks really cool :(

Why not the MIT or Apache license?

**Comment by 0x326** [comment]
Are you making a derivative work of `autojump`? I'm curious why you can't

**Comment by wting** [comment]
GPLv3 is a fairly aggressive copyleft license which understandably some companies will not allow use of.

My newer projects typically use MIT, but GPLv3 is something chosen by the original author of autojump and I'm inclined to respect that decision.

There are many autojump alternatives that may have a more appropriate license I would suggest using (e.g. https://github.com/rupa/z).
