### ISSUE TITLE
autojump/j not working in Raspberry Pi OS 32bit (debian buster)

### ISSUE THREAD

**Issue by bassamanator** [wting/autojump#610]
I did the manual install. Added ```[[ -s /home/pi/.autojump/etc/profile.d/autojump.sh ]] && source /home/pi/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u```
to the end of .zshrc.

When I do ```autojump testdirectory``` or ```j testdirectory``` (testdirectory exists btw) the shell says ```.``` and the directory doesn't change.

**Comment by suzaku** [comment]
Maybe you want to give [shonenjump](https://github.com/suzaku/shonenjump) a try instead.

**Comment by MikeFoden** [comment]
@bassamanator did you navigate to this directory before trying to use autojump?

You can use `j -s` to see it has been seen before and to learn its weighting.

**Comment by bassamanator** [comment]
So I didn't make any changes at all but things are working on my RPI now. I have been updating it and what not...

**Comment by MikeFoden** [comment]
That's because you have been building up autojump's cache. 👍🏻

**Comment by bassamanator** [comment]
Can that possibly be correct? I was doing ```j actualDirName``` which used to result in a ```.``` and the directory wouldn't change.

**Comment by MikeFoden** [comment]
It only knows of folders when you have been to them, so it can cache its location.
