### ISSUE TITLE
Please explain why this is better than cd

### ISSUE THREAD

**Issue by mabushey** [wting/autojump#611]
I installed this, added it to my .zshrc file. After a few minutes I came to the conclusion that cd with zsh history completion is much better. I see absolutely no advantage to this utility. I uninstalled it, but you might want to explain for the next person who comes along why anyone would feel this is faster or better. I don't. I'm boggled how this project has 11.6k stars. Someone should explain why.

**Comment by wting** [comment]
Sorry autojump wasn't useful for you.

**Comment by mabushey** [comment]
Don't be sorry, and I'm not trying to be mean. I just don't get it, I think your project should, at the top of the readme, state why it's useful with examples demonstrating this.

**Comment by pkoch** [comment]
I felt like https://github.com/wting/autojump#usage described it pretty decently. Can you give an example of what you'd wish you had encountered?

**Comment by mabushey** [comment]
Hi @pkoch . My guess is once you're already familiar with autojump, the usage is perfectly clear. For example, `Jump To A Child Directory:` `jc bar`. That's EXACTLY the same as `cd bar`. I get that you could have a dir of `/this/path/goes/to/foo' and you could type `j foo`, I just don't see how that's any better than in zsh typing `cd /th` and up-arrow to retrieve the full path out of history. This is a mindset difference that the docs do not communicate.

**Comment by pkoch** [comment]
One thing that's very obvious to me is that, with `cd` and `C-r`ing, you have to know the full path. In some project layouts, that's not necessarily a given, and it's a bunch more keystrokes (which makes a real difference for some folks in the way that they express themselves). One case that makes it pretty obvious would be the inbox example at the end of usage.

I think we might have a way to turn your frustration into a commit that's useful for others too. But, given that the current README has worked so far, the brunt would naturally fall on you. If you can shape up a draft of a PR that you think will be useful for folks coming from the "just `C-r` it" camp, that might be a good starting point. If not, welp, let's wait for someone with more ardor or more directly actionable insights. Given this project is a voluntary lead effort, we need concrete steps forward, lest we drown in the dreams and wishes of everyone.

Thanks for your input, and for focusing on being kind when things turned sour!
