### ISSUE TITLE
How to use auto jump with fish on Termux?

### ISSUE THREAD

**Issue by forliuyifei** [wting/autojump#629]
```
Failed to execute process '/data/data/com.termux/files/home/.autojump/bin/autojump'. Reason:
The file '/data/data/com.termux/files/home/.autojump/bin/autojump' specified the interpreter '/usr/bin/env python', which is not an executable command.
[: Missing argument at index 2

~/.autojump/share/autojump/autojump.fish (line 53):
            if [ $output = "." ]
               ^
in function 'j' with arguments 'A'

(Type 'help [' for related documentation)
autojump: directory 'A' not found



Try `autojump --help` for more information.
```

**Comment by pl643** [comment]
I came across this because I had python3 installed and don't have a python link to python3.  The below fish snippet got me working.
   ln -sf (which python3) /bin/python

**Comment by WayneTian-42** [comment]
> I came across this because I had python3 installed and don't have a python link to python3. The below fish snippet got me working.
> ln -sf (which python3) /bin/python

Can you teach me how to fix this problem more detailedly? I'm new to fish and don't know what to do.
