### ISSUE TITLE
For M1 chips, install correctly but not working.

### ISSUE THREAD

**Issue by GeojoL** [wting/autojump#656]
do not use this 

`[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh`

try this 

 `[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && source /opt/homebrew/etc/profile.d/autojump.sh`

I did not use oh-my-zsh, I put this straight to the .bash_profile, it will also work if you put it to .zshrc.

I tried 
` sh /opt/homebrew/etc/profile.d/autojump.sh`
and

`. /opt/homebrew/etc/profile.d/autojump.sh`
it does not work. maybe because of using subshell.

![image](https://user-images.githubusercontent.com/97789539/181682288-9ca8ae76-4f07-4610-8c2e-8f6d3dc02125.png)
![image](https://user-images.githubusercontent.com/97789539/181682333-a45514b1-a078-49e2-ab43-2edcc08194b5.png)

**Comment by yanaiela** [comment]
Did you install it with brew?
It doesn't work for me
