### ISSUE TITLE
Suggestion: cd into typed dir if available

### ISSUE THREAD

**Issue by indeedwatson** [wting/autojump#657]
Example:

If I do
`j my_dir` when there is no `my_dir` in the jump list, *but there is* `./my_dir`, then automatically cd into it.

**Comment by dragonfly1033** [comment]
I would also find this useful as it would allow me to just use j for everything. If implementing the feature is not possible then perhaps exit with an error so we can do something like
`alias j='temp_func(){ j "$1" || cd "$1"; unset -f temp_func; }; temp_func'`

which is just an alias that runs your argument on j and then cd if j fails.

**Comment by adelowo** [comment]
Do not alias `j` command. Fixed mine.

**Comment by wting** [comment]
While I understand it would be helpful to change directory based on the current path if it hasn't already been indexed, I don't want to overlap features between autojump and `cd`.

From [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy):

> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".
