### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by kishaningithub** [wting/autojump#662]
First of all thanks a lot for creating autojump. Have been using it for several years now and i cant think of working on a machine without this installed.

I see the last commit in this repo [was on 2018](https://github.com/wting/autojump/commits/master)

Just concerned over the maintenance of this repo

**Comment by wting** [comment]
Yup, but I'm primarily concerned with security issues for now.

**Comment by kishaningithub** [comment]
@wting If possible, Can you review and merge the PRs that are open, IMO this will give a great morale boost to the contributors of this repo?
