### ISSUE TITLE
How to fix when I input '-' , but terminal show '_j:compadd:5: bad option: -_'

### ISSUE THREAD

**Issue by ningyougan** [wting/autojump#667]
hi,

I install autojump by clone repo then run `python install.py`

when i run shell

```bash
# i want todo
j -h
```

```bash
# but terminal show
_j:compadd:5: bad option: -_
_j:compadd:5: bad option: -_
_j:compadd:5: bad option: -_
_j:compadd:5: bad option: -_
_j:compadd:5: bad option: -_
```

I use macos add zsh.

**Comment by spydon** [comment]
Check in the section for Known issues:
https://github.com/wting/autojump#known-issues

> autojump does not support directories that begin with -.
