### ISSUE TITLE
Manually declare a directory

### ISSUE THREAD

**Issue by tortolo** [wting/autojump#90]
This is a feature that may be nice for users: a way to tell that this directory is to be considered as frequently used.

Typical use case: I create a directory for a project I shall work on for the next few weeks. Right now, it is not yet often used, but it will be, and having it at a high position in autojump's list would save me time for the beginning.

**Comment by saltcod** [comment]
For anyone else having issues here:

On MacOS, my autojump.txt file is in `~/Library/autojump/autojump.txt`  

When autojump brings me to the wrong directory, I'll delete entries in autojump.txt and retrain it. 

ie: I try and jump to a directory called `matter`, but it always brought me to a different `news-matters` directory. To fix this, I just delete all of the lines in autojump.txt for `news-matters`.  

Hope this helps someone else!
